export const GET_CHAIR_LIST = 'GET_CHAIR_LIST';
export const CHOICE_CHAIR = 'CHOICE_CHAIR';
export const DAT_VE_THANH_CONG = 'DAT_VE_THANH_CONG';
export const SET_LOADING = 'SET_LOADING';
export const SET_BTN_LOADING = 'SET_BTN_LOADING';
